version: '3.4'

services:
  swm-sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: swm-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - "1433:1433"
    volumes:
      - ./.swm-sqlserver-data:/var/opt/mssql/data
      